server:
  port: 8082

spring:
  application:
    name: book-service
  datasource:
    url: jdbc:mysql://localhost:3306/bookdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
